export * from './lib/sw-client.module';
export * from './lib/sw-client.service';
export * from './lib/types/responses/film';
export * from './lib/types/responses/planet';
export * from './lib/types/responses/people';
export * from './lib/types/responses/species';
export * from './lib/types/responses/starship';
export * from './lib/types/responses/vehicle';
export * from './lib/types/responses/paginated';